name: build adocs and publish v1 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      files: |
        docs/index.html text/html nb
        docs/images/Digdir.png image/png nb images/Digdir.png
        docs/images/NG_organisering.png image/png nb images/NG_organisering.png
        docs/images/NG_roller.png image/png nb images/NG_roller.png
        docs/images/NG_utviklingsfaser.png image/png nb images/NG_utviklingsfaser.png
      host: https://data.norge.no
      ontology: nasjonale-grunndata-rammeverk
      ontology-type: specification
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
